# Generated by Django 5.1.4 on 2025-01-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poro',
            name='region',
            field=models.CharField(choices=[('F', 'Freljord'), ('D', 'Demacia'), ('I', 'Ionia'), ('N', 'Noxus'), ('P', 'Piltover & Zaun'), ('S', 'Shadow Isles'), ('B', 'Bilgewater'), ('T', 'Targon'), ('SH', 'Shurima'), ('BC', 'Bandle City'), ('R', 'Runterra')], max_length=100),
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
                ('poro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.poro')),
            ],
        ),
    ]
